name: libsql_dart_example
description: "Demonstrates how to use the libsql_dart plugin."

publish_to: "none"

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  libsql_dart:
    path: ../
  flutter_bloc: ^8.1.6
  provider: ^6.1.2
  path: ^1.9.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
